/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.projectagent.controller;import cn.zhuatech.projectagent.common.ApiResponse;import cn.zhuatech.projectagent.service.ProjectActionExecutionService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                       */
@RestController @RequestMapping("/api/enterprise/projectagent")public class ProjectActionExecutionController{private final ProjectActionExecutionService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                        */
public ProjectActionExecutionController(ProjectActionExecutionService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/project-action-execution")public ApiResponse<ProjectActionExecutionService.Assessment>assess(@Valid @RequestBody ProjectActionExecutionService.Request request){return ApiResponse.ok(service.assess(request));}}
