/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.projectagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                     */
class ProjectActionExecutionServiceTest{private final ProjectActionExecutionService s=new ProjectActionExecutionService();/**
                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                               */
@Test void executesGovernedAction(){var r=s.assess(new ProjectActionExecutionService.Request("A1",true,true,true,true,true,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(ProjectActionExecutionService.Decision.EXECUTE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void coordinatesOperationalGaps(){var r=s.assess(new ProjectActionExecutionService.Request("A2",true,true,true,true,true,true,true,false,false,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@Test void blocksUnauthorizedAction(){var r=s.assess(new ProjectActionExecutionService.Request("A3",false,false,false,false,false,false,false,true,false,true,true,false));assertThat(r.blockers()).hasSize(9);}}
